version: '3.7'

services:
  postgres:
    container_name: postgres_online_registration
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/online_registration
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
    
volumes:
  mongodb_data:
   driver: local
   

  