spring:
  application:
    name: online-registration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false

